config:
  warningsAsErrors: true

comments:
  AbsentOrWrongFileLicense:
    active: true
    licenseTemplateFile: "detekt-license.template"
    licenseTemplateIsRegex: true
    excludes:
      - 'gradlew'
      - 'gradlew/wrapper/*'