config:
  warningsAsErrors: true

comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes:
      - 'gradlew'
      - 'gradlew/wrapper/*'
    licenseTemplate: |
      /*
       * Copyright (c)