[bundles]


[plugins]

[versions]

agp = "9.0.0"
jreleaser = "1.22.0"

[libraries]

agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
jreleaserGradlePlugin = { group = "org.jreleaser", name = "org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
