
[bundles]


[plugins]

androidxRoom = { id = "androidx.room", version.ref = "androidxRoom" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
# Do not remove, use as "id" instead of alias, this is why it is not detected.
composePlugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
lbDetekt = { id = "studio.lunabee.plugin.detekt", version.ref = "lbDetekt" }

[versions]

agp = "9.0.0"
androidToolsDesugarJdkLibs = "2.1.5"
androidxActivity = "1.12.4"
androidxAppcompat = "1.7.1"
androidxCore = "1.17.0"
androidxExifinterface = "1.4.2"
androidxFragment = "1.8.9"
androidxGlance = "1.1.1"
androidxHiltNavigationCompose = "1.3.0"
androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.7"
androidxPaging = "3.4.1"
androidxPreference = "1.2.1"
androidxRecyclerview = "1.4.0"
androidxRoom = "2.8.4"
androidxSqlite = "2.6.2"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"
coil = "2.7.0"
composeBom = "2026.02.00"
composeMultiplatform="1.10.1"
composeNavigation = "2.9.2"
core = "1.17.0"
dagger = "2.59.1"
dokka = "2.2.0-Beta"
googleAndroidMaterial = "1.13.0"
hbb20Countrycodepicker = "2.7.3"
javapoet = "1.13.0"
jetbrainsCompose ="1.10.1"
jetbrainsMaterial3="1.9.0"
jreleaser = "1.22.0"
junit4 = "4.13.2"
junitJupiter = "6.0.2"
koin = "4.1.1"
kotlin = "2.3.10"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerialization = "1.10.0"
kotlinxViewModel="2.9.6"
ksp = "2.3.5"
ktor = "3.4.0"
lbDetekt = "2.0.6"
libphonenumber = "9.0.24"
lifecycleViewmodelAndroid = "2.10.0"
lint = "32.0.0"
mockk = "1.14.9"
normalize = "1.3.3"
okhttp = "5.3.2"
robolectric = "4.16.1"
touchlabKermit = "2.0.8"
touchlabSkie = "0.10.10"
zoomable = "2.11.0"

[libraries]

agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidxAppcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidxComposeUiTestJunit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidxCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxExifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "androidxExifinterface" }
androidxFragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidxGlanceWidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }
androidxHiltNavigationCompose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidxLifecycleCommon = { group = "androidx.lifecycle", name = "lifecycle-common", version.ref = "androidxLifecycle" }
androidxLifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "androidxLifecycle" }
androidxLifecycleRuntime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "androidxLifecycle" }
androidxLifecycleRuntimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidxLifecycleViewmodelAndroid = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-android", version.ref = "lifecycleViewmodelAndroid" }
androidxPagingCommon = { group = "androidx.paging", name = "paging-common", version.ref = "androidxPaging" }
androidxPreferenceKtx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidxRecyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }
androidxRoomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidxRoomPaging = { group = "androidx.room", name = "room-paging", version.ref = "androidxRoom" }
androidxRoomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidxSqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "androidxSqlite" }
androidxTestCoreKtx = { group = "androidx.test", name = "core-ktx", version.ref = "androidxTestCore" }
androidxTestRunner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidxUiTest = { module = "androidx.compose.ui:ui-test" }
androidxUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidxUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidxUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidxUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coilCompose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coilComposeSvg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeFoundation = { group = "androidx.compose.foundation", name = "foundation" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
composeMaterialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
composeNavigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
composePlugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
composeRuntime = { module = "androidx.compose.runtime:runtime" }
composeUi = { group = "androidx.compose.ui", name = "ui" }
composeUiTest = { group = "androidx.compose.ui", name = "ui-test" }
composeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
composeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
composeUiUnit = { module = "androidx.compose.ui:ui-unit" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
desugarJdk = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidToolsDesugarJdkLibs" }
dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
googleAndroidMaterial = { group = "com.google.android.material", name = "material", version.ref = "googleAndroidMaterial" }
hbb20Countrycodepicker = { group = "com.hbb20", name = "ccp", version.ref = "hbb20Countrycodepicker" }
hiltAndroid = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hiltAndroidCompiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
hiltCore = { group = "com.google.dagger", name = "hilt-core", version.ref = "dagger" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
jetbrainsComponentsResources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrainsCompose" }
jetbrainsFoundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrainsCompose" }
jetbrainsMaterial3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrainsMaterial3" }
jetbrainsRuntime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrainsCompose" }
jetbrainsUi = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrainsCompose" }
jreleaserGradlePlugin = { group = "org.jreleaser", name = "org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitJupiterBom = { group = "org.junit", name = "junit-bom", version.ref = "junitJupiter" }
junitJupiterPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }
koinAndroid = { group = "io.insert-koin", name = "koin-android" }
koinBom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }
koinCompose = { group = "io.insert-koin", name = "koin-compose" }
koinComposeViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koinCore = { group = "io.insert-koin", name = "koin-core" }
koinViewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinTestJunit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinxCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesBom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinxCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinxDatetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxViewModel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "kotlinxViewModel" }
ktorClientAndroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientIos = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }
ktorContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorJsonSerialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
libphonenumber = { group = "com.googlecode.libphonenumber", name = "libphonenumber", version.ref = "libphonenumber" }
lintApi = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lintChecks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
navigationCompose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
normalize = { group = "com.doist.x", name = "normalize", version.ref = "normalize" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
touchlabKermit = { group = "co.touchlab", name = "kermit", version.ref = "touchlabKermit" }
touchlabKermitCrashlytics = { group = "co.touchlab", name = "kermit-crashlytics", version.ref = "touchlabKermit" }
touchlabSkie = { group = "co.touchlab.skie", name = "co.touchlab.skie.gradle.plugin", version.ref = "touchlabSkie" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }
